steps:
  - name: golang:1.20
    args:
      - '-c'
      - >
        go install github.com/jstemmer/go-junit-report/v2@latest

        2>&1 go test -timeout 1m -v ./... | /go/bin/go-junit-report
        -set-exit-code -iocopy -out ${SHORT_SHA}_test_log.xml
    id: Test
    entrypoint: /bin/bash
  - name: 'docker'
    entrypoint: 'sh'
    args: [ '-c', 'docker build -t $_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA .' ]
    id: Build
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
    id: Push
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args:
      - beta
      - run
      - jobs
      - update
      - $_SERVICE_NAME
      - '--image=$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
      - '--region=$_DEPLOY_REGION'
      - '--quiet'
    id: Deploy
    entrypoint: gcloud
images:
  - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
options:
  substitutionOption: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _PLATFORM: managed
  _SERVICE_NAME: countmein-stats
  _LABELS: gcb-trigger-id=a2e47103-7a5b-47a7-b79f-a0febd6b213f
  _TRIGGER_ID: a2e47103-7a5b-47a7-b79f-a0febd6b213f
  _DEPLOY_REGION: me-west1
  _GCR_HOSTNAME: eu.gcr.io
tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - countmein-stats